services:
  # SERVICE 1: The Database (MySQL)
  db:
    image: mysql:8.0
    container_name: driver_db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: driver_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # SERVICE 2: The Cache (Redis)
  redis:
    image: redis:alpine
    container_name: driver_redis_container
    ports:
      - "6379:6379"

  # SERVICE 3: Metabase Analytics Dashboard
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3001:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      - db
      - redis

volumes:
  db_data:
  metabase_data: